### ISSUE TITLE
To do idea 4: two-way coupling between ice flow and hydrology

### ISSUE THREAD

**Issue by jkingslake** [ldeo-glaciology/nye_eqns_bvp#5]
Construct (or adapt, see https://github.com/ldeo-glaciology/nye_eqns_bvp/issues/4#issue-1012241372) an ice flow model so that, given an effective pressure field, it simulates H, grounding line position and sliding speed, which are then used to evolve the drainage system forward in time, which in turn defines the effective pressure field.

**Comment by glugeorge** [comment]
Completed, in new repository: https://github.com/glugeorge/coupled_ice_hydrology
