### ISSUE TITLE
Convert MATLAB code to Python

### ISSUE THREAD

**Issue by glugeorge** [ldeo-glaciology/nye_eqns_bvp#8]
Adding just to track it

**Comment by glugeorge** [comment]
The code is now functionally the same (will push commit shortly) - however there are some leftover issues that need to be looked into. First, my earlier python bugs weren't actually bugs - it's actually the MATLAB code that was wrong and I didnt properly adjust for velocity. I had only ever subtracted the original velocity, so now when correcting for that, the velocity at the lake exit gets too fast and causes the cross sectional area to drop below zero (i.e. the conduit seals). 

Next, there seems to be some issues making the colorplots with large sets of datapoints - the kernel seems to crash and restart. I dont think this is an error on my end and rather an issue with pcolormesh

**Comment by jkingslake** [comment]
Were the issues you mention above fixed? 
If so, worth noting here. 
Also for future reference, linking to the notebook that you mention above is a good idea.

**Comment by glugeorge** [comment]
Yes the issues above have resolved (with my updated code which i will push shortly)
